# Generated by Django 3.0.7 on 2021-07-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20210718_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
