# Generated by Django 3.0.7 on 2021-07-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_auto_20210720_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
