# Generated by Django 3.0.7 on 2021-07-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_project_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='youtube',
            field=models.URLField(blank=True, default=''),
        ),
    ]
