# Generated by Django 3.0.7 on 2021-07-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_info_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='linkdin',
            field=models.URLField(blank=True, default=''),
        ),
    ]
